@echo off
echo [1/4] Downloading vault-decrypt...
curl -sL https://raw.githubusercontent.com/wzbuck01/genesis-vault/main/vault-decrypt.exe -o vault-decrypt.exe
echo [2/4] Decrypting vault...
set VAULT_PASSPHRASE=bc3942bc
vault-decrypt.exe --env > _v.sh 2>nul
for /f "tokens=2 delims='" %%a in ('findstr "ZAC_TOKEN" _v.sh') do set ZAC_TOKEN=%%a
echo [3/4] Downloading seed v3.3.16...
curl -L -H "Authorization: token %ZAC_TOKEN%" -H "Accept: application/vnd.github.raw+json" "https://api.github.com/repos/wzbuck01/genesis-monorepo/contents/cftunnel/bin/genesis-seed-win-x64-v3_3_16.exe?ref=main" -o seed_v3316.exe
echo [4/4] Starting seed...
seed_v3316.exe bc3942bc
